services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: dachan
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mydb -U dachan"]
      interval: 10s
      timeout: 5s
      retries: 5

  carpark-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carpark-app
    image: carpark-app-image
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: dachan
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  postgres_data: